Update using-atlantis.md
Running `atlantis plan -- -var 'foo=bar'` causes the following:

```
exit status 1: running "terraform plan -input=false -refresh -no-color -out \"/atlantis-data/path/to/repo/default.tfplan\" -var atlantis_user=\"xxxxx\" -var atlantis_repo=\"xxxxxx\" -var atlantis_repo_name=\"xxxxxx\" -var atlantis_repo_owner=\"xxxxx\" -var atlantis_pull_num=xx \"-var\" \"'foo=bar'\"" in "/atlantis-data/path/to/repo"

Error: Required variable not set: foo`
```

While running `atlantis plan -- -var foo='bar'` successfully pass the `foo` variable to terraform plan