Fix docker-entrypoint when called with atlantis
Prior to v0.22.0 the container could be run with the command `atlantis
server`. However this was broken by #2770:
```
Error: unknown command "atlantis" for "atlantis"
```

This PR reverts to previous functionality and matches the comment.
Following calls all work again:
```sh
docker run atlantis server
docker run atlantis --help
docker run atlantis atlantis server
docker run atlantis atlantis --help
```